spring.application.name=airline-management-system
spring.datasource.url=jdbc:mysql://localhost:3306/airline
spring.datasource.username=root
spring.datasource.password=JavaDeveloper@1998
spring.jpa.hibernate.ddl-auto=update
springdoc.swagger-ui.path=/swagger-ui.html


jwt.secret=EjbNd8P1sQwUzHrFbK5gLoYtVmXp2sJcR6e9QaZhT0vXyWhBkNi7MdCgPlTrAeBu
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000
